openapi: "3.0.1"
info:
  title: Catalog API
  version: "0.1.0"
paths:
  /catalog/items:
    get:
      summary: List catalog items
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object

