openapi: "3.0.1"
info:
  title: Order API
  version: "0.1.0"
paths:
  /orders:
    post:
      summary: Create order
      responses:
        '201':
          description: Created
  /orders/{orderId}:
    get:
      summary: Get order status
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK

