openapi: "3.0.1"
info:
  title: Payment API
  version: "0.1.0"
paths:
  /payments/initiate:
    post:
      summary: Initiate payment
      responses:
        '202':
          description: Accepted
  /payments/callback:
    post:
      summary: Payment gateway callback
      responses:
        '200':
          description: OK

